// data/schools.js — Cornwall (curated, real businesses, Aug 2026)
// Facet field: levels (array) — Beginner / Intermediate / Advanced / Kids
window.LISTINGS = [
  // ---- Newquay ----
  { name: "Cornish Wave Surf School", country: "England", region: "Cornwall", town: "Newquay",
    url: "https://cornishwave.com",
    blurb: "Small-group surf coaching on Towan and Fistral from a friendly, long-running local school — plus coasteering and SUP.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/cornishwave/", facebook: "https://www.facebook.com/cornishwave", youtube: "https://www.youtube.com/c/Cornishwave" },
    levels: ["Beginner", "Intermediate", "Kids"] },
  { name: "Escape Surf School", country: "England", region: "Cornwall", town: "Newquay",
    url: "https://www.escapesurfschool.co.uk",
    blurb: "Specialist surf-only school on the Towan cliff top, with ex-pro head coaches and daily lessons for every level.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/escape.surf.school/", facebook: "https://www.facebook.com/EscapeSurfSchool" },
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  { name: "Fistral Beach Surf School", country: "England", region: "Cornwall", town: "Newquay",
    url: "https://www.fistralbeachsurfschool.co.uk",
    blurb: "Right on the sand at Fistral with one of the UK's largest surf-hire fleets — lessons for all abilities, open all year.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/fistralbeachsurfschool/", facebook: "https://www.facebook.com/fistralbeachsurfschool" },
    levels: ["Beginner", "Intermediate", "Advanced"] },
  { name: "NQY Surf School", country: "England", region: "Cornwall", town: "Newquay",
    url: "https://www.newquaysurfingschool.com",
    blurb: "Beach-front school on Great Western led by four-time UK champion Adam Griffiths — lessons, hire and coasteering.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/nqysurfschool/", facebook: "https://www.facebook.com/nqysurfschool" },
    levels: ["Beginner", "Intermediate", "Kids"] },
  { name: "Westcountry Surf School", country: "England", region: "Cornwall", town: "Watergate Bay",
    url: "https://surfingschool.co.uk",
    blurb: "Small-group and private lessons from Watergate Bay, with a camper-van shuttle to the break and a café on site.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate"] },
  // ---- Bude ----
  { name: "Big Blue Surf School", country: "England", region: "Cornwall", town: "Bude",
    url: "https://www.bigbluesurfschool.com",
    blurb: "Bude's original surf school (est. 1999) on Summerleaze Beach — all abilities and adaptive lessons, open year-round.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/bigbluesurfschool/", facebook: "https://www.facebook.com/BigBlueSurfSchool" },
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  // ---- Polzeath ----
  { name: "George's Surf School", country: "England", region: "Cornwall", town: "Polzeath",
    url: "https://www.georgessurfschool.com",
    blurb: "Bespoke private coaching at Polzeath and Harlyn — an ISA/Surfing England Centre of Excellence with video analysis.",
    image: "", verified: false,
    socials: { facebook: "https://www.facebook.com/GeorgesSurfSchoolPolzeath" },
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  // ---- Harlyn / Padstow ----
  { name: "Harlyn Surf School", country: "England", region: "Cornwall", town: "Harlyn",
    url: "https://www.harlynsurfschool.co.uk",
    blurb: "Cornwall's longest-established school (since 1994) on sheltered Harlyn Bay — surf, SUP, kayak and coasteering.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/harlynsurfschool/", facebook: "https://www.facebook.com/harlynsurfschool", x: "https://x.com/harlynsurfschl" },
    levels: ["Beginner", "Intermediate", "Kids"] },
  // ---- Perranporth ----
  { name: "Stoked Surf School", country: "England", region: "Cornwall", town: "Perranporth",
    url: "https://stokedsurfschool.co.uk",
    blurb: "Perranporth's year-round school with a permanent base, on-site surf-and-skate shop and a structured progression system.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/stoked_surf_school/", facebook: "https://www.facebook.com/surfperranporth2022", youtube: "https://www.youtube.com/@stokedsurfschool" },
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  { name: "Perranporth Surf School", country: "England", region: "Cornwall", town: "Perranporth",
    url: "https://www.perranporthsurfschool.co.uk",
    blurb: "Perranporth's original surf school (est. 2004) — quality, fun lessons for all abilities right on the beach.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/perransurfschool/", facebook: "https://www.facebook.com/perranporthsurfschool" },
    levels: ["Beginner", "Intermediate", "Kids"] },
  // ---- St Agnes ----
  { name: "Breakers Surf School", country: "England", region: "Cornwall", town: "St Agnes",
    url: "https://surf-lessons.co.uk",
    blurb: "Sheltered Trevaunance Cove school with strong local knowledge — lessons, SUP and a kids' club, open all year.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/breakerssurfschool/", facebook: "https://www.facebook.com/breakerssurfsch" },
    levels: ["Beginner", "Intermediate", "Kids"] },
  // ---- Gwithian / Hayle ----
  { name: "Gwithian Academy of Surfing", country: "England", region: "Cornwall", town: "Gwithian",
    url: "https://www.surfacademy.co.uk",
    blurb: "ASI-accredited academy (est. 1999) on gently shelving Gwithian Beach — beginner to competition coaching with video analysis.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/gwithianacademyofsurfing/", facebook: "https://www.facebook.com/Gwithian.Academy.of.Surfing" },
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  { name: "Shore Surf School", country: "England", region: "Cornwall", town: "Hayle",
    url: "https://shoresurf.com",
    blurb: "One of St Ives Bay's longest-running schools (est. 1999), with lessons and hire across two Hayle-side locations.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Kids"] },
  // ---- St Ives ----
  { name: "St Ives Surf School", country: "England", region: "Cornwall", town: "St Ives",
    url: "https://www.stivessurfschool.co.uk",
    blurb: "St Ives' only surf school, on blue-flag Porthmeor by the Tate — a Surfing England Centre of Excellence, plus SUP and coasteering.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/stivessurfschool/", facebook: "https://www.facebook.com/stivessurfschool", tiktok: "https://www.tiktok.com/@stivessurfschool" },
    levels: ["Beginner", "Intermediate", "Kids"] },
  // ---- Sennen Cove ----
  { name: "Sennen Surfing Centre", country: "England", region: "Cornwall", town: "Sennen Cove",
    url: "https://sennensurfingcentre.co.uk",
    blurb: "Award-winning O'Neill academy on the golden sands of Sennen, near Land's End — one of the UK's longest-running surf schools.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/sennensurfcentre/", facebook: "https://www.facebook.com/sennensurfing" },
    levels: ["Beginner", "Intermediate"] },
  // ---- Croyde ----
  { name: "Surfing Croyde Bay", country: "England", region: "Devon", town: "Croyde",
    url: "https://surfingcroydebay.co.uk",
    blurb: "Surfing England Centre of Excellence at Baggy Point with a 6:1 ratio, on-site cafe, sauna and cold plunge — lessons, hire and coasteering.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/surfingcroyde/", facebook: "https://www.facebook.com/surfingcroydebay" },
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  { name: "Surf South West", country: "England", region: "Devon", town: "Croyde",
    url: "https://www.surfsouthwest.com",
    blurb: "Croyde's original surf school (since 1996), an award-winning Centre of Excellence running lessons at Croyde and Saunton, plus adaptive coaching.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/surfsouthwest/", x: "https://x.com/surfsouthwest" },
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  // ---- Saunton ----
  { name: "Walking on Waves Surf School", country: "England", region: "Devon", town: "Saunton",
    url: "https://walking-on-waves.com",
    blurb: "Saunton's original surf school, run by local surfers for 20+ years — small-group, private and kids' lessons on 3.5 miles of gentle sand.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  { name: "Surf Saunton", country: "England", region: "Devon", town: "Saunton",
    url: "https://www.surf-saunton.co.uk",
    blurb: "Beachfront school on Saunton Sands teaching beginner to advanced, with beach yoga and sauna sessions.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/surfsaunton/" },
    levels: ["Beginner", "Intermediate", "Advanced"] },
  // ---- Woolacombe ----
  { name: "Woolacombe Surf Centre", country: "England", region: "Devon", town: "Woolacombe",
    url: "https://www.woolacombesurfcentre.com",
    blurb: "Woolacombe's highest-rated school and a Surfing England Centre of Excellence — surf lessons plus coasteering, kayak and SUP.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/woolacombesurfcentre/", facebook: "https://www.facebook.com/woolacombesurfcentre", x: "https://x.com/WoolacombeSurf" },
    levels: ["Beginner", "Intermediate", "Advanced"] },
  // ---- Westward Ho! ----
  { name: "The North Devon Surf School", country: "England", region: "Devon", town: "Westward Ho!",
    url: "https://www.northdevonsurfschool.co.uk",
    blurb: "Westward Ho!'s purpose-built Centre of Excellence (since 1988) with a Level 4 coach, 50m from the beach, open year-round.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/northdevonsurfschool/", facebook: "https://www.facebook.com/northdevonsurfschool", x: "https://x.com/northdevonsurf" },
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  { name: "Westward Waves Surf School", country: "England", region: "Devon", town: "Westward Ho!",
    url: "https://www.westwardwavessurfschool.co.uk",
    blurb: "Family-run school on Westward Ho!'s Blue Flag beach — friendly group and private lessons for all abilities from a converted horse box.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/westwardwaves/" },
    levels: ["Beginner", "Intermediate", "Kids"] },
  // ---- Putsborough ----
  { name: "Nick Thorn Surf Coaching", country: "England", region: "Devon", town: "Putsborough",
    url: "https://nickthorn.com",
    blurb: "Level 4 Master Surf Coach running small-group and private lessons at sheltered Putsborough, for ages 6 to 80 — plus coasteering and SUP.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/nickthornsurfcoaching/", x: "https://x.com/NickThornSurf" },
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  // ---- Bigbury-on-Sea / Bantham (South Devon) ----
  { name: "Discovery Surf School", country: "England", region: "Devon", town: "Bigbury-on-Sea",
    url: "https://discoverysurf.com",
    blurb: "South Devon's original surf school (est. 2002), family-run across Bigbury-on-Sea and Bantham with small ratios, a kids' surf club and adaptive lessons.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/discoverysurfschool/", facebook: "https://www.facebook.com/discoverysurfschool" },
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  // ---- Llangennith ----
  { name: "The Welsh Surfing Federation Surf School", country: "Wales", region: "Swansea", town: "Llangennith",
    url: "https://surfschool.wsf.wales",
    blurb: "Llangennith's original surf school, run by the Welsh Surfing Federation since 1981 on one of Wales' most consistent beaches — lessons for every level.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  { name: "Progress Surf School", country: "Wales", region: "Swansea", town: "Llangennith",
    url: "https://www.swanseasurfing.com",
    blurb: "A Surfing Wales Centre of Excellence with 25+ years on Gower, teaching at Llangennith and sheltered Caswell — plus women's sessions and kids' clubs.",
    image: "", verified: false,
    socials: { facebook: "https://www.facebook.com/progresssurf" },
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  // ---- Caswell Bay ----
  { name: "Gower Surf Academy", country: "Wales", region: "Swansea", town: "Caswell Bay",
    url: "https://www.gowersurfing.com",
    blurb: "Caswell Bay's friendly, all-year school (also at Rhossili in summer) — group, family, kids and one-to-one lessons from qualified local coaches.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/gowersurfing/", facebook: "https://www.facebook.com/gowersurfacademy" },
    levels: ["Beginner", "Intermediate", "Kids"] },
  { name: "Surfability UK", country: "Wales", region: "Swansea", town: "Caswell Bay",
    url: "https://www.surfabilityukcic.org",
    blurb: "An award-winning charity at Caswell Bay making surfing accessible to people with disabilities and additional needs, with adaptive equipment and trained volunteers.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Kids"] },
  // ---- Rhossili ----
  { name: "Bae Surf School", country: "Wales", region: "Swansea", town: "Rhossili",
    url: "https://www.baesurfschool.com",
    blurb: "Small-group lessons and squad coaching on the dramatic sands of Rhossili and Llangennith, with low instructor ratios and plenty of water time.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced"] },

  // ================= PORTUGAL =================
  // ---- Ericeira (Lisbon) ----
  { name: "Ericeira Surf School", country: "Portugal", region: "Lisbon", town: "Ericeira",
    url: "https://ericeirasurfschool.pt",
    blurb: "Portuguese Surf Federation-certified school at Ribeira d'Ilhas and Foz do Lizandro, run by veteran local Michel Amaro — small groups of six, lessons and guiding for every level.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/ericeirasurfschool/" },
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  { name: "Ericeira Waves Surf School", country: "Portugal", region: "Lisbon", town: "Ericeira",
    url: "https://www.ericeirawaves.com",
    blurb: "FPS-certified instructors with water-safety qualifications running beginner-focused lessons at Ericeira's iconic beaches, plus quality rentals — safety-first and family-friendly.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/ericeirawavessurfschool/" },
    levels: ["Beginner", "Intermediate", "Kids"] },
  { name: "Blue Ocean Surf School", country: "Portugal", region: "Lisbon", town: "Ericeira",
    url: "https://www.blueoceansurfschool.com",
    blurb: "One of Ericeira's oldest schools, right on Ribeira d'Ilhas beach inside the World Surfing Reserve, with 20+ years' experience and Portuguese, English and Spanish-speaking coaches.",
    image: "", verified: false,
    socials: { instagram: "https://www.instagram.com/ericeirablueocean/" },
    levels: ["Beginner", "Intermediate", "Advanced"] },
  { name: "Magikvanilla Surf School", country: "Portugal", region: "Lisbon", town: "Ericeira",
    url: "https://www.magikvanilla.com",
    blurb: "Small-group lessons capped at five per coach with FPS- and ISA-certified instructors who are also qualified lifeguards — single sessions or stacked over a week.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced"] },
  { name: "Surf Riders & Co", country: "Portugal", region: "Lisbon", town: "Ericeira",
    url: "https://www.surfriders.pt",
    blurb: "Ericeira school and surf camp running all-level lessons from its shop in the town centre, with family and kids' classes and a tight local crew since 2016.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  // ---- Costa da Caparica (Lisbon) ----
  { name: "Caparica Surf School", country: "Portugal", region: "Lisbon", town: "Costa da Caparica",
    url: "https://caparicasurfschool.pt",
    blurb: "Certified Costa da Caparica school teaching since 2000 — personalised lessons from beginner to advanced, board hire and surf-fitness training, 20 minutes from Lisbon.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced"] },
  { name: "Caparica Surf Academy", country: "Portugal", region: "Lisbon", town: "Costa da Caparica",
    url: "https://caparicasurfacademy.com",
    blurb: "FPS-accredited school at Praia da Rainha whose coaches are Lusofona University surf graduates — lessons for all ages plus SUP and bodyboard, on the doorstep of Lisbon.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Kids"] },
  { name: "Surf Pro Surf School", country: "Portugal", region: "Lisbon", town: "Costa da Caparica",
    url: "https://surfpro.pt",
    blurb: "Costa da Caparica school certified by the Portuguese Surf Federation and Turismo de Portugal, with personalised small-group coaching at Praia do Norte.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Kids"] },
  // ---- Cascais (Lisbon) ----
  { name: "Karma Surf School", country: "Portugal", region: "Lisbon", town: "Cascais",
    url: "https://karmasurfschool.com",
    blurb: "FPS/ISA-accredited mobile school teaching around Cascais, Guincho and Carcavelos — chasing the day's best beach, with low ratios and lessons for kids, beginners and advanced surfers.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  // ---- Baleal (Peniche) ----
  { name: "Baleal Surf Camp", country: "Portugal", region: "Peniche", town: "Baleal",
    url: "https://www.balealsurfcamp.com",
    blurb: "The area's original surf camp and school (est. 1993) on Cantinho da Baia beach — FPS-certified, with all-level lessons plus kids' and family courses right on the sand.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  { name: "Baia de Peniche Surf School", country: "Portugal", region: "Peniche", town: "Baleal",
    url: "https://www.penichesurfbaia.com",
    blurb: "Baleal school and camp owned by a European Bodyboard Champion, with small-group surf and bodyboard lessons, rentals and hands-on coaching.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced"] },
  { name: "Silver Coast Surf School", country: "Portugal", region: "Peniche", town: "Baleal",
    url: "https://www.surfingsilvercoast.com",
    blurb: "Surf lessons, rentals and accommodation in Baleal, a village on the Peniche peninsula widely rated one of Europe's most consistent surf spots.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate"] },
  // ---- Peniche (Peniche) ----
  { name: "Peniche Surf Camp", country: "Portugal", region: "Peniche", town: "Peniche",
    url: "https://www.penichesurfcamp.com",
    blurb: "Long-running Peniche school (founded 2004) with all-level lessons, 200+ rental boards and ocean-view accommodation, a short walk from several surf spots.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced"] },
  // ---- Lagos (Algarve) ----
  { name: "Algarve Watersport", country: "Portugal", region: "Algarve", town: "Lagos",
    url: "https://algarvewatersport.com",
    blurb: "Lagos multi-sport school running surf lessons for 20 years, with IPDJ- and ASI-certified coaches, transport included and small groups on the western Algarve's best beaches.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced"] },
  { name: "FilSurf Surf School", country: "Portugal", region: "Algarve", town: "Lagos",
    url: "https://www.filsurf.com",
    blurb: "Family-run Lagos school since 2008, fully licensed across the western Algarve, with friendly certified instructors teaching beginners and improvers, kids and adults.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Kids"] },
  { name: "Lagos Surf Safari", country: "Portugal", region: "Algarve", town: "Lagos",
    url: "https://lagossurfsafari.com",
    blurb: "Accredited Lagos school running daily surf trips from Lagos and Praia da Luz to the day's best west- or south-coast break, for absolute beginners through to guided sessions.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  // ---- Sagres (Algarve) ----
  { name: "Algarve Surf School", country: "Portugal", region: "Algarve", town: "Sagres",
    url: "https://www.algarvesurfschool.com",
    blurb: "One of Portugal's longest-running schools, started in Sagres 25 years ago — all-level lessons at Mareta and Amado, with an affordable, sociable surf camp and hostel.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  { name: "FreeRide Surfing", country: "Portugal", region: "Algarve", town: "Sagres",
    url: "https://frsurf.com",
    blurb: "Sagres school since 2002 offering lessons, camps, guiding and rentals around Cordoama, with certified local instructors and surf-and-stay packages.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced"] },
  { name: "Good Feeling Surf School", country: "Portugal", region: "Algarve", town: "Sagres",
    url: "https://goodfeelingsurfschool.com",
    blurb: "FPS-certified Sagres school running since 1997, with small year-round groups, family and kids' packs, based at a laid-back surf camp in nearby Raposeira.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] },
  { name: "Wavesensations", country: "Portugal", region: "Algarve", town: "Sagres",
    url: "https://wavesensations.com",
    blurb: "Family-run Sagres surf school, shop and rentals in one, reading the conditions daily to teach at Tonel, Mareta and beyond — group, private and kids' classes with certified instructors.",
    image: "", verified: false,
    socials: {},
    levels: ["Beginner", "Intermediate", "Advanced", "Kids"] }
];
