// functions/marketplace/[slug].ts — GET /marketplace/:slug (no trailing slash)
//
// Every internal link generated by this site uses trailing-slash directory
// URLs. The real handler lives at marketplace/[slug]/index.ts to match that
// convention; this just redirects the bare form for robustness against
// external links/typos.

import type { Env, PagesFunction } from "../../lib/types";

export const onRequestGet: PagesFunction<Env> = async ({ request }) => {
  const url = new URL(request.url);
  return Response.redirect(url.origin + url.pathname + "/" + url.search, 301);
};
